language: node_js
node_js:
  - 8
sudo: required

services:
  - docker

cache:
  npm: false

before_install:
  - npm i
  - npm run build
  - npm run lint

script:
  - docker build -t public-webapp -f Dockerfile .
