language: node_js
node_js:
  - 15
sudo: required

services:
  - docker

cache:
  npm: false

before_install:
  - npm i -g npm@6
  - npm run build
  - npm run lint

script:
  - docker build -t public-webapp -f Dockerfile .
