language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t public-webapp -f Dockerfile .

script:
  - docker run -e CI=true public-webapp yarn test

after_success:
  - docker build -t public-webapp .
