language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t webapp-production -f Dockerfile.dev .

script:
  - docker run -e CI=true webapp-production npm run test

after_success:
  - docker build -t webapp-production .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push webapp-production
