version: "3.1"
services:
  public-webapp:
    container_name: public-webapp
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - sparow-core
    stdin_open: true
    tty: true
networks:
  sparow-core:
    external: false
