# This is a basic workflow to help you get started with Actions
name: Push Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install packages
        run: yarn
      - name: Build project
        run: npm run build
