# This is a basic workflow to help you get started with Actions
name: Push Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install packages
        run: yarn
      - name: Build the project
        run: npm run build --if-present
      - name: Deploy by FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_FTP_USERNAME }}
          password: ${{ secrets.SERVER_FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: build/
          server-dir: /var/www/sparow/public-webapp/
          dry-run: true
