# This is a basic workflow to help you get started with Actions
name: Push Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install packages
        run: yarn
      - name: Build the project
        run: npm run build --if-present
      - name: ssh-scp-deploy
        uses: marcodallasanta/ssh-scp-deploy@v.1.0.2
        with:
          local: ./build
          remote: /var/www/sparow/webapp
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_SSH_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
