# This is a basic workflow to help you get started with Actions
name: Push Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install packages
        run: yarn
      - name: Build the project
        run: npm run build --if-present
      - name: Simple FTP deploy
        # You may pin to the exact commit or the version.
        # uses: kevinpainchaud/simple-ftp-deploy-action@2c6e7dfe809abd4f8f687a78b5d79efaf5c439ad
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          # FTP host
          ftp_host: ${{ secrets.SERVER_IP }}
          # FTP username
          ftp_username: ${{ secrets.SERVER_FTP_USERNAME }}
          # FTP password
          ftp_password: ${{ secrets.SERVER_FTP_PASSWORD }}
          # The local folder to copy
          local_source_dir: ./build
          # The remote folder
          dist_target_dir: /var/www/sparow/public-webapp
